### PR TITLE
Fix typos in readme

### PR DESCRIPTION
**Pull request by Kaisrlik**

### CODE REVIEW

**Comment by ppisa** [comment]
Patch applied to the master.

**Comment by fvacek** [comment]
Why didn't you simply merge this request, does this project have some special merge policy?

**Comment by ppisa** [comment]
I tend to prefer linear history for the start when only small changes (documentation only in this case) are applied. May it be there is option to rebase during interactive merge which would be better (I have not checked). For sure for larger code contributions, it worth to consider real merge but anyway, branch based on the actual master is easier in such case as well. Patch preserves authorship so I do not consider its use as a real problem. If the project has more active developers, then the value of documenting start of branch would prevail over simplicity of linear history.

**Comment by Cynerd** [comment]
@ppisa if you want to have clean history but you work with github PR or gitlab MR then you can first do rebase, force push and then merge. That keeps clean history and at the same time is compatible with pull/merge workflow.

I commonly use `git merge --ff-only` to merge to master. It is good practice because if CI is used then head merged to master is tested. On patch application or merge with commit the top commit has to be tested again and that does not ensure that tip in master always passes tests (at least on CI).

**Pull request closed without merging**
